language: node_js
node_js:
 - "node"
deploy:
 provider: elasticbeanstalk
 access_key_id: $ACCESSKEYID
 secret_access_key:
   secure: "$SECRETACCESSKEY"
 region: "ap-southeast-2"
 app: "smash-facts"
 env: "SmashFacts-env"
 bucket_name: "elasticbeanstalk-ap-southeast-2-628122790516"